version: "3"

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DB_HOSTNAME=postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fcc-python-api-tutorial
    volumes:
    - fcc-postgres-db:/var/lib/postgresql/data
volumes:
  fcc-postgres-db: