name: Build and Deploy Code

on: [push, pull_request]

jobs:
  setup-codebase:
    runs-on: ubuntu:latest
    steps:
      - name: Pull codebase
        uses: actions/checkout@v2
      - name: Install Python v3.9
        uses: actions/setup-python@v2
          with:
            python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install codebase dependencies
        run: pip install -r requirements.txt